project:
  type: website

website:
  title: "Chris Y. Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: Blog
      - href: coursework.qmd
        text: Coursework
      - href: resume.qmd
        text: Resume

theme: darkly 
format: html