project:
  type: website

website:
  title: "Chris Yuhan Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - url: <a target="_blank" rel="noopener noreferrer" href="https://cliuc.github.io/chrisliu/media/LiuChris_Resume.pdf">Link</a>
        text: Résumé
        
theme: darkly 
format: html