project:
  type: website

website:
  title: "Chris Yuhan Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - url: https://www.chrisyliu.com/media/LiuChris_Resume.pdf
        text: Résumé
        
theme: darkly 
format: html